[project]
name = "shellshock-scope"
version = "0.1.0"
description = "A simple (non intrusive) trainer for [ShellShock Live]"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keyboard>=0.13.5",
    "pyautogui>=0.9.54",
    "pywin32>=310",
]
